name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: waka-box
        uses: matchai/waka-box@v4.0.5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 69b676d72f2fa0d14caa3d40a40766d7
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
